blueprints/admin.py
import os
from datetime import datetime

from flask import Blueprint, render_template, request, jsonify, current_app
from sqlalchemy import not_
from sqlalchemy.orm import aliased
from werkzeug.utils import secure_filename

from decorators import check_admin, check_root
from exts import db
from models import BorrowHistoryModel, UserModel, BooksModel, TagModel

bp = Blueprint('admin', __name__, url_prefix='/admin')


@bp.route('/index')
@check_admin
def index():
    return render_template('admin_borrow.html')


# 图书出借
@bp.route('/lend_book', methods=['GET', 'POST'])
@check_admin
def lend_book():
    if request.method == 'GET':
        return render_template('admin_borrow.html')
    else:
        form = request.form
        username = form.get('username')
        card = form.get('libraryCardNo')
        bookid = form.get('bookID')
        print(bookid)
        bookTitle = form.get('bookTitle')
        # 查询当前图书的借阅状态
        existing_loan = (
            BorrowHistoryModel.query
            .filter(BorrowHistoryModel.book_id == bookid, BorrowHistoryModel.return_date.is_(None))
            .first()
        )
        if existing_loan:
            # 图书已被借出且未归还，返回警告信息
            return render_template('admin_borrow.html', alert_message="该图书已被借出，尚未归还！")
        # 查询读者信息
        reader_book_info = (
            db.session.query(
                UserModel.id.label('reader_id'),
                BooksModel.id.label('book_id')
            )
            .join(BooksModel, BooksModel.id == bookid)
            .filter(UserModel.username == username)
            .first()
        )
        reader_id = reader_book_info.reader_id
        book_id = reader_book_info.book_id
        # 添加新的借阅记录
        new_loan = BorrowHistoryModel(
            reader_id=reader_id,
            book_id=book_id,
            borrow_date=datetime.now(),
            return_date=None
        )
        db.session.add(new_loan)
        db.session.commit()
        # 成功借阅，返回正常页面（传递 alert_message）
        return render_template('admin_borrow.html', alert_message="图书借阅成功！")


@bp.route('/return_book', methods=['GET', 'POST'])
@check_admin
def return_book():
    if request.method == 'GET':
        return render_template('admin_return.html')
    else:
        form = request.form
        username = form.get('username')
        card = form.get('libraryCardNo')
        bookid = form.get('bookID')
        bookTitle = form.get('bookTitle')
        reader_id = UserModel.query.filter(UserModel.username == username).first().id
        book_id = BooksModel.query.filter(BooksModel.Name == bookTitle).first().id
        question = BorrowHistoryModel(reader_id=reader_id, book_id=book_id, borrow_date=datetime.now(),
                                      return_date=None)
        db.session.add(question)
        db.session.commit()
        return render_template('admin_borrow.html')


@bp.route('/search_name', methods=['POST'])
def search_name():
    library_card_no = request.form.get('libraryCardNo')
    # print(library_card_no)
    if library_card_no:
        try:
            username = UserModel.query.filter(UserModel.card == library_card_no).first().username
            # print(username)
            return jsonify({'username': username})
        except:
            return jsonify({'username': ''})
    else:
        try:
            bookId = request.form.get('bookID')
            bookTitle = BooksModel.query.filter(BooksModel.id == bookId).first().Name
            print(bookTitle)
            return jsonify({'bookTitle': bookTitle})
        except:
            return jsonify({'bookTitle': ''})


@bp.route('/search_book', methods=['POST'])
def search_book():
    library_card_no = request.form.get('libraryCardNo')
    # 首先根据卡号查询用户ID
    user = UserModel.query.filter_by(card=library_card_no).first()

    if user:
        # 创建一个别名以方便查询关联的借阅历史记录
        history_alias = aliased(BorrowHistoryModel)

        # 根据用户ID查询该用户的借阅历史记录并关联到对应的书籍信息
        borrowed_books = (db.session.query(BooksModel)
                          .join(history_alias, BooksModel.id == history_alias.book_id)
                          .filter(history_alias.reader_id == user.id,
                                  history_alias.return_date.is_(None))
                          # .filter(history_alias.return_date==None)
                          .all())

        # 转换为 JSON 格式返回给前端
        book_list = [{'book_id': book.id, 'title': book.Name} for book in borrowed_books]
        print(book_list)
        return jsonify({'books': book_list})
    else:
        return jsonify({'error': '未找到对应卡号的用户'}), 404


@bp.route('/del_book', methods=['POST'])
def del_book():
    library_card_no = request.form.get('libraryCardNo')
    bookId = request.form.get('bookId')
    reader_id = UserModel.query.filter_by(card=library_card_no).first().id
    book = BorrowHistoryModel.query.filter_by(book_id=bookId, reader_id=reader_id, return_date=None).first()
    book.return_date = datetime.now()
    db.session.commit()
    print(reader_id, bookId)
    return jsonify({"success": "sss"})


@bp.route('/add_book', methods=['GET', 'POST'])
def add_book():
    if request.method == 'GET':
        return render_template('admin_add_book.html')
    else:
        # print(request.form)
        Name = request.form.get('Name')
        Author = request.form.get('Author')
        Publisher = request.form.get('Publisher')
        Synopsis = request.form.get('Synopsis')
        Price = request.form.get('Price')
        cover_image = request.files['CoverImage']
        if cover_image:
            filename = secure_filename(cover_image.filename)  # 使用安全的文件名
            cover_image.save(os.path.join(current_app.root_path, 'static/images', filename))  # 保存到images文件夹
            Cover = filename  # 将保存后的文件名赋值给变量Cover
        else:
            Cover = None  # 如果未上传封面，则设置为None
        book = BooksModel(Name=Name, Author=Author, Publisher=Publisher, Synopsis=Synopsis, Price=Price,Cover=Cover)
        db.session.add(book)
        db.session.commit()
        return render_template('admin_add_book.html', message="图书添加成功")


@bp.route('/search_tags', methods=['GET', 'POST'])
def search_tags():
    if request.method == 'GET':
        return render_template('add_tags.html')
    else:
        try:
            bookId = request.form.get('bookID')
            # print(bookId)
            book = BooksModel.query.filter_by(id=bookId).first()
            bookName = book.Name
            # print(bookName)
            tags = book.Tags
            # print(tags)
            tags = [{'id': tag.id, 'name': tag.name} for tag in tags]
            # print(tags)
            return jsonify({"books": bookName, "tags": tags})
        except:
            return jsonify({'tags': []})


@bp.route('/add_tags', methods=['GET', 'POST'])
@check_admin
def add_tags():
    if request.method == 'GET':
        return render_template('add_tags.html')
    else:
        tag = request.form.get('add-tag')
        flg = TagModel.query.filter_by(name=tag).first()
        bookId = request.form.get('bookID')
        book = BooksModel.query.filter_by(id=bookId).first()
        print(flg)
        if not flg:
            tags = TagModel(name=tag)
            db.session.add(tags)
            db.session.commit()
            flg1 = TagModel.query.filter_by(name=tag).first()
            book.Tags.append(flg1)
        else:
            book.Tags.append(flg)
        db.session.add(book)
        db.session.commit()
        return render_template('add_tags.html')


@bp.route('/list_book', methods=['GET', 'POST'])
@check_admin
def list_book():
    page = request.args.get('page', type=int, default=1)
    per_page = 15  # 每页显示的数据条数，可以根据需要调整
    search_query = request.args.get('q', type=str, default='')  # 获取搜索关键词

    if search_query:
        books = BooksModel.query.filter(
            BooksModel.Name.ilike(f'%{search_query}%') |
            BooksModel.Author.ilike(f'%{search_query}%')
        ).paginate(page=page, per_page=per_page)
    else:
        books = BooksModel.query.paginate(page=page, per_page=per_page)

    return render_template('list_book.html', books=books.items, pagination=books, current_route="hide")


@bp.route('/book_detail/<int:book_id>')
@check_admin
def book_detail(book_id):
    book = BooksModel.query.filter_by(id=book_id).first()
    return render_template("update_book_detail.html", book=book)


@bp.route('/update_book', methods=['POST'])
def update_book():
    q = request
    id = q.form.get('id')
    name = q.form.get('bookName')
    Publisher = q.form.get('Publisher')
    Synopsis = q.form.get('Synopsis')
    Author = q.form.get('Author')
    Price = q.form.get('Price')
    book = BooksModel.query.filter_by(id=id).first()
    # 更新记录
    if book:
        book.Name = name
        book.Synopsis = Synopsis
        book.Author = Author
        book.Price = Price
        book.Publisher = Publisher
        # 提交数据库事务（如果你使用的是支持事务的ORM，如SQLAlchemy）
        db.session.commit()
        return jsonify({"success": "sss"})
    else:
        print(f"找不到名为《{name}》的图书")
        return jsonify({"error": "sss"})


@bp.route('/del_tag')
def del_tag():
    tagId = request.args.get('tag_id')
    bookId = request.args.get('book_id')
    # print(tagId,bookId)
    tag = TagModel.query.filter_by(id=tagId).first()
    book = BooksModel.query.filter_by(id=bookId).first()
    try:
        tag.books.remove(book)
        db.session.commit()
        return jsonify({"success": True})
    except Exception as e:
        db.session.rollback()  # 出现错误时回滚事务
        print(f"An error occurred: {e}")
        return jsonify({"error": False})


@bp.route('/admin_user_purview')
@check_root
def admin_user_purview():
    page = request.args.get('page', type=int, default=1)
    per_page = 20  # 每页显示的数据条数，可以根据需要调整
    search_query = request.args.get('q', type=str, default='')  # 获取搜索关键词
    # 筛除 root 用户并根据搜索关键词过滤
    query = UserModel.query.filter(not_(UserModel.username == 'root'))
    if search_query:
        query = query.filter(

blueprints/auth.py
import random

from flask import Blueprint, render_template, jsonify,redirect,url_for,session
from werkzeug.security import generate_password_hash,check_password_hash#负责用来加密密码

from exts import mail, db
from flask_mail import Message
from flask import request
import string
from models import EmailCaptchaModel,UserModel
from .forms import ReservationForm,LoginForm
from datetime import datetime

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/login',methods=['GET','POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user=UserModel.query.filter_by(email=email).first()
            if not user:
                print("邮箱不存在")
                return redirect(url_for("auth.login"))
            if check_password_hash(user.password,password):
                session['user_id'] = user.id
                return redirect("/")
            else:
                print("密码错误")
                return redirect(url_for("auth.login"))

        else:
            print(form.errors)
            return redirect(url_for("auth.login"))

@bp.route('/logout')
def logout():
    session.clear()
    return redirect("/")


@bp.route('/register',methods=['GET','POST'])
def register():
    # 验证用户提交的邮箱和验证码是否对应以及正确
    #表单验证flask-wtf:wtforms
    if request.method == 'GET':
        return render_template('register.html')
    else:
        # 验证用户提交的邮箱和验证码是否对应以及正确
        # 表单验证flask-wtf:wtforms
        form=ReservationForm(request.form)
        if form.validate():
            email=form.email.data
            username=form.username.data
            password=form.password.data
            card="US"+datetime.now().strftime("%Y%m%d")
            user=UserModel(username=username,password=generate_password_hash(password),card=card,email=email)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("auth.login"))
        else:
            print(form.errors)
            return redirect(url_for("auth.register"))

# 邮箱验证码
@bp.route('/captcha/email')
def get_email_captcha():
    email = request.args.get('email')  # 获取邮箱(args参数)
    # 4/6：随机数组，字母、数字和大小写
    source = string.digits * 4
    captcha = random.sample(source, 4)
    captcha = "".join(captcha)
    message = Message('注册验证码', recipients=[email], body=f"您本次的验证码是:{captcha}")
    mail.send(message)
    # memcached/redis
    # 用数据库表的方式存储
    email_captcha = EmailCaptchaModel(email=email, captcha=captcha)
    db.session.add(email_captcha)
    db.session.commit()
    # restful api
    return jsonify({"code": 200, "msg": "发送成功", "data": None})


@bp.route('/mail/test')
def mail_test():
    message = Message('邮箱测试', recipients=["865648178@qq.com"], body="这是一条测试的玩意!")
    mail.send(message)
    return "邮件发送成功"

blueprints/qa.py
from flask import Blueprint, render_template, request
from sqlalchemy.orm import aliased

from exts import db
from models import BooksModel, TagModel
from flask import Blueprint, render_template, request
from flask_sqlalchemy import pagination

from models import BooksModel, TagModel

# import pandas as pd
bp = Blueprint('qa', __name__, url_prefix='/')


@bp.route('/')
def index():
    # questions = QuestionModel.query.order_by(QuestionModel.content_time.desc()).all()
    # books = BooksModel.query.all()
    return render_template('index.html')


@bp.route('/qa/detail/<qa_id>')
def qa_book_detail(qa_id):
    book = BooksModel.query.get(qa_id)
    return render_template('BookDetail.html', book=book)


@bp.route('/search')
def search():
    page = request.args.get('page', 1, type=int)  # 获取当前页码，默认为1
    per_page = 10  # 每页显示的数据条数
    q = request.args.get('BookName')
    books_query = BooksModel.query.filter(BooksModel.Name.contains(q))
    pagination = books_query.paginate(page=page, per_page=per_page, error_out=False)
    books = pagination.items
    return render_template("library-index.html", books=books, pagination=pagination, q=q,mode="bookName")


@bp.route('/search-tag')
def search_tag():
    page = request.args.get('page', 1, type=int)  # 获取当前页码，默认为1
    per_page = 10  # 每页显示的数据条数
    tag_name = request.args.get('tag_name')
    books = BooksModel.query.join(TagModel, BooksModel.Tags).filter(TagModel.name == tag_name).paginate(page=page, per_page=per_page, error_out=False)
    print(books.items)
    return render_template("library-index.html", books=books.items, pagination=books, q=tag_name,mode="tagName")

blueprints/user.py
from collections import defaultdict

from flask import Blueprint, render_template, request, g

from decorators import check_user
from exts import db
from models import BorrowHistoryModel, UserModel

bp = Blueprint('user', __name__, url_prefix='/user')


@bp.route('/')
@check_user
def index():
    return render_template("user_base.html")


@bp.route('/history_user')
@check_user
def history_user():
    page = request.args.get('page', type=int, default=1)
    per_page = 5
    user_id = g.user.id
    borrow_histories = (
        db.session.query(BorrowHistoryModel)
        .join(UserModel, UserModel.id == BorrowHistoryModel.reader_id)
        .filter(UserModel.id == user_id)
        .order_by(BorrowHistoryModel.borrow_date.desc())
        # .all()
    )
    books=borrow_histories.paginate(page=page, per_page=per_page)
    return render_template("user_history.html", books=books.items, pagination=books,current_route="hide")


@bp.route('/user_detail')
@check_user
def user_detail():
    user_id = g.user.id
    user = UserModel.query.filter_by(id=user_id).first()
    # print(user)
    return render_template("user_detail.html", user=user)


@bp.route('/user_update')
@check_user
def user_update():
    id = request.args.get('id')
    username = request.args.get('username')
    email = request.args.get('email')
    sex = request.args.get('sex')
    admin = request.args.get('admin')
    user = UserModel.query.filter_by(id=id).first()
    if user:
        user.username = username
        user.email = email
        user.sex = sex
        user.admin = admin
        user.email = email
        # 提交数据库事务
        try:
            db.session.commit()
            message = "操作成功！"
            return render_template("user_detail.html", userd=user, alert_message=message)
        except Exception as e:
            print(e)
            message = "操作失败！"
            db.session.rollback()
            return render_template("user_detail.html", userd=user, alert_message=message)
    else:
        print(f"找不到名为{username}的用户")
        return render_template("user_detail.html", userd=user)


@bp.route('/user_not_return')
@check_user
def user_not_return():
    page = request.args.get('page', type=int, default=1)
    per_page = 5
    user_id = g.user.id
    borrow_histories = (
        db.session.query(BorrowHistoryModel)
        .join(UserModel, UserModel.id == BorrowHistoryModel.reader_id)
        .filter(UserModel.id == user_id, BorrowHistoryModel.return_date.is_(None))
        .distinct(BorrowHistoryModel.book_id)
    )
    books = borrow_histories.paginate(page=page, per_page=per_page)
    return render_template("user_not_return.html", books=books.items,pagination=books, current_route="hide")

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <!-- 加一行测试注释 -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap.4.6.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/init.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/admin.css') }}">
    <title>{% block title %}{% endblock %}</title>
    <!--    详情页面自己的css,js都放在header当中-->
    {% block head %}{% endblock %}
    <!--    标题自定义-->
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">首页</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% if user.admin in [2,3] and user %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('admin.lend_book') }}">出借</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('admin.return_book') }}">返还</a>
                    </li>
                {% elif user.admin==1 %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.index') }}">用户界面</a>
                    </li>
                {% endif %}
                <li class="nav-item ml-2">
                    {#                        <form class="form-inline my-2 my-lg-0" method="GET" action="{{url_for('qa.search')}}">#}
                    <form class="form-inline my-2 my-lg-0" method="GET" action="{{ url_for('qa.search') }}">
                        <input class="form-control mr-sm-2" type="search" placeholder="请输入图书名" aria-label="Search"
                               name="BookName">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                    </form>
                </li>
            </ul>

            <ul class="navbar-nav">
                {% if user %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.index') }}"><span href="#">{{ user.username }}</span></a>
                        {#                        <span class="nav-link" href="#">{{ user.username }}</span>#}
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">退出登录</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">登录</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.register') }}">注册</a>
                    </li>
                {% endif %}
            </ul>

        </div>
    </div>
</nav>
<div class="parent-container" style="display: flex; flex-direction: row;">
    {% if user.admin in [2,3] and user %}
        <div class="nav" style="width: 200px;">
            <ul class="left-nav">
                <a href="{{ url_for('admin.lend_book') }}">
                    <div>图书借阅</div>
                </a>
                <a href="{{ url_for('admin.return_book') }}">
                    <div>图书归还</div>
                </a>
                <a href="{{ url_for('admin.add_book') }}">
                    <div>图书入库</div>
                </a>
                <a href="{{ url_for('admin.add_tags') }}">
                    <div>标签管理</div>
                </a>
                <a href="{{ url_for('admin.list_book') }}">
                    <div>图书管理</div>
                </a>
                {% if user.admin == 3 and user %}
                    <a href="{{ url_for('admin.admin_user_purview') }}">
                        <div>用户管理</div>
                    </a>
                    <a href="{{ url_for('admin.admin_user_borrow') }}">
                        <div>借阅管理</div>
                    </a>
                {% endif %}
                <!-- 更多链接... -->
            </ul>
        </div>
    {% else %}

    {% endif %}
    <div class="container" id="bbody" {% if current_route == "hide" %} style="margin-left: 0;"{% endif %}>

        <div class="content">
            {% block body %}{% endblock %}
        </div>
    </div>
</div>
</body>
</html>

templates/user_history.html
{% extends "user_base.html" %}

{% block title %}{{ user.username }}的图书历史{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
    {#    <link rel="stylesheet" href="{{url_for('static',filename='css/admin.css')}}">#}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/user.css') }}">

{% endblock %}
{% block body %}
    {#     <div class="row" style="margin-top: 20px;width: 100%">#}
    {#            <div class="col"></div>#}
    <div class="col-10">
        <ul class="question-ul" style="padding-left: 0">
            {% for book in books %}
                <li>
                    <div class="side-question">
                        <img class="side-question-avatar" src="../static/images/{{ book.books.Cover }}" alt="">
                    </div>
                    <div class="question-main">
                        <div class="question-title"><a
                                href="{{ url_for('qa.qa_book_detail',qa_id = book.books.id) }}">{{ book.books.Name }}</a></div>
                        <div class="book-tags">
                            {% for tag in book.books.Tags %}
                                <a href="{{ url_for('qa.search_tag',tag_name = tag.name) }}">
                                    <button style="display: inline-block">{{ tag.name }}</button>
                                </a>
                            {% endfor %}
                        </div>
                        <div class="question-content">简介：{{ book.books.Synopsis }}</div>
                        <div class="question-detail">
                            <span class="question-author">借出时间：{{ book.borrow_date }}</span>
                            {% if book.return_date %}
                            	<span class="question-time">收录日期：{{ book.return_date }}</span>
                            {% endif %}
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
{% if pagination %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if pagination.has_prev %}
                        <li class="page-item">
                            <a class="page-link"
                               href="{{ url_for('user.history_user', BookName=q, page=pagination.prev_num) }}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                    {% endif %}

                    {% for page_num in pagination.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                        {% if page_num %}
                            {% if page_num == pagination.page %}
                                <li class="page-item active" aria-current="page">
                                    <a class="page-link" href="#">{{ page_num }}</a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link"
                                       href="{{ url_for('user.history_user', page=page_num) }}">{{ page_num }}</a>
                                </li>
                            {% endif %}
                        {% else %}
                            <li class="page-item disabled"><span class="page-link">...</span></li>
                        {% endif %}
                    {% endfor %}

                    {% if pagination.has_next %}
                        <li class="page-item">
                            <a class="page-link"
                               href="{{ url_for('qa.search', BookName=q, page=pagination.next_num) }}"
                               aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
{% endblock %}

templates/user_not_return.html
{% extends "user_base.html" %}

{% block title %}{{ user.username }}的已借出图书{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/user.css') }}">

{% endblock %}
{% block body %}
    <div class="col-10">
        <ul class="question-ul" style="padding-left: 0">
            {% for book in books %}
                <li>
                    <div class="side-question">
                        <img class="side-question-avatar" src="../static/images/{{ book.books.Cover }}" alt="">
                    </div>
                    <div class="question-main">
                        <div class="question-title"><a
                                href="{{ url_for('qa.qa_book_detail',qa_id = book.books.id) }}">{{ book.books.Name }}</a></div>
                        <div class="book-tags">
                            {% for tag in book.books.Tags %}
                                <a href="{{ url_for('qa.search_tag',tag_name = tag.name) }}">
                                    <button style="display: inline-block">{{ tag.name }}</button>
                                </a>
                            {% endfor %}
                        </div>
                        <div class="question-content">简介：{{ book.books.Synopsis }}</div>
                        <div class="question-detail">
                            <span class="question-author">借阅时间：{{ book.borrow_date }}</span>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
    {% if pagination %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if pagination.has_prev %}
                        <li class="page-item">
                            <a class="page-link"
                               href="{{ url_for('user.user_not_return', BookName=q, page=pagination.prev_num) }}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                    {% endif %}

                    {% for page_num in pagination.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                        {% if page_num %}
                            {% if page_num == pagination.page %}
                                <li class="page-item active" aria-current="page">
                                    <a class="page-link" href="#">{{ page_num }}</a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link"
                                       href="{{ url_for('user.user_not_return', page=page_num) }}">{{ page_num }}</a>
                                </li>
                            {% endif %}
                        {% else %}
                            <li class="page-item disabled"><span class="page-link">...</span></li>
                        {% endif %}
                    {% endfor %}

                    {% if pagination.has_next %}
                        <li class="page-item">
                            <a class="page-link"
                               href="{{ url_for('qa.search', BookName=q, page=pagination.next_num) }}"
                               aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
{% endblock %}